### ISSUE TITLE
https

### ISSUE THREAD

**Issue by janroesler** [burning-duck/burning-duck#12]
No more to say ^^

**Comment by janroesler** [comment]
@pbit  i thing i need your help on this issue. With ssl or tls i have no clue 😄

**Comment by pbit** [comment]
@janroesler Sounds like NET ;)

We need this anyway, lets try it tomorrow with https://letsencrypt.org/

**Comment by janroesler** [comment]
Have used this tutorial https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04 , but dont get it running. I am stuck on point "How To Use the Webroot Plugin". I don't know whats wrong 😞 @pbit

**Comment by janroesler** [comment]
Working now, but the tomcat need some changes for ssl.

**Comment by janroesler** [comment]
So now all is working, the tomcat connector has the localhost alias. But i think the problem was that the public instance hasn't run all install tasks. And some configuration was missing in the backend. 

But burning-duck.de ist online 😀 😄 , so issue closed.
