### ISSUE TITLE
Add a section / paragraph component

### ISSUE THREAD

**Issue by pbit** [burning-duck/burning-duck#2]
Just text and heading.
Helps in structuring content (visual and logical).

**Comment by janroesler** [comment]
Oh ok, now i get it, this component we can use for #3 :)

**Comment by janroesler** [comment]
So i have split the configuration a little bit in the commit 3115f9ca53a16f0b3e260ab7ace4685848cac77b 

Now we have under `/common/fields` the `semantic-ui-color-select.yaml` and the `semantic-ui-size-select.yaml`. Now this fields are reusable.

**Comment by janroesler** [comment]
And commit c5be22a18b459a7604b715d2be17b7487917213d , add a simple paragraph component.
- headline
- text
- hr 

Need some styling i think, but for now it is ok.
I close this issue!
