### ISSUE TITLE
Add a ToC component.

### ISSUE THREAD

**Issue by pbit** [burning-duck/burning-duck#3]
Needs #2 .
A table of content to navigate in page.
Should render all Sections on the page.

**Comment by janroesler** [comment]
I think we can use the components on the page.
For example:
If we run through the main area an get the child nodes.
![image](https://cloud.githubusercontent.com/assets/2596518/25449352/ceb1f6f0-2abb-11e7-9809-8831a13b7829.png)

We can use a title property (section title) as link name and the jcr:uuid as anchor.
So we need to at a section name field for each component or a section component.
And we need the jcr:uui from the meta data or @id 

Or what is your idea ? @pbit

**Comment by pbit** [comment]
Sounds good, just keep it simple for the first implementation.
If we get unexpected entries in we couls just add a little checkbox *showInNavigation* like the pages do.

**Comment by janroesler** [comment]
So i split the main area in three sub areas.
So we can add a simple navigation on the left side.
We can check if the burning-duck:components/paragraph is there and can link the uuid i think.

Will test that 🐤

**Comment by janroesler** [comment]
So i add a table of content component.
This component get his parent and then the child "mainContent".
Runs over all components and checks if it is a burning-duck:components/paragraph component.
Then it create a link with the uuid as hash.
And the paragraph has an div with the uuid as id.

Works local. 
I close the issue 🏆
