### ISSUE TITLE
Create a version badge/info component.

### ISSUE THREAD

**Issue by pbit** [burning-duck/burning-duck#4]
I hate to read an article only to find out it doesnt work on my version of code.
So provide a simple way to say "This article works with Cerebral 2 and Magnolia 5.5"...

**Comment by pbit** [comment]
Semantic UI:

![image](https://cloud.githubusercontent.com/assets/683376/24986937/61e2d6de-1ffd-11e7-8aff-bb03048cfbbf.png)

**Comment by janroesler** [comment]
Ok, i think a multi value field will do the trick.
But should we use a select- or text-field ??

**Comment by pbit** [comment]
Added labeGroup and labelItem component.
